// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: GRPC/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidderID  int32 `protobuf:"varint,1,opt,name=BidderID,proto3" json:"BidderID,omitempty"`
	Amount    int32 `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Timestamp int32 `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *BidInfo) Reset() {
	*x = BidInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidInfo) ProtoMessage() {}

func (x *BidInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidInfo.ProtoReflect.Descriptor instead.
func (*BidInfo) Descriptor() ([]byte, []int) {
	return file_GRPC_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidInfo) GetBidderID() int32 {
	if x != nil {
		return x.BidderID
	}
	return 0
}

func (x *BidInfo) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BidInfo) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_GRPC_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_proto_proto_rawDescGZIP(), []int{2}
}

type CurrentResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status          string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	HighestBid      int32  `protobuf:"varint,2,opt,name=HighestBid,proto3" json:"HighestBid,omitempty"`
	HighestBidderID int32  `protobuf:"varint,3,opt,name=HighestBidderID,proto3" json:"HighestBidderID,omitempty"`
}

func (x *CurrentResult) Reset() {
	*x = CurrentResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentResult) ProtoMessage() {}

func (x *CurrentResult) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentResult.ProtoReflect.Descriptor instead.
func (*CurrentResult) Descriptor() ([]byte, []int) {
	return file_GRPC_proto_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CurrentResult) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *CurrentResult) GetHighestBidderID() int32 {
	if x != nil {
		return x.HighestBidderID
	}
	return 0
}

var File_GRPC_proto_proto protoreflect.FileDescriptor

var file_GRPC_proto_proto_rawDesc = []byte{
	0x0a, 0x10, 0x47, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x47, 0x52, 0x50, 0x43, 0x22, 0x5b, 0x0a, 0x07, 0x42, 0x69, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x1d, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x71, 0x0a, 0x0d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x12, 0x28,
	0x0a, 0x0f, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74,
	0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x49, 0x44, 0x32, 0x65, 0x0a, 0x0e, 0x41, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x42, 0x69,
	0x64, 0x12, 0x0d, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x42, 0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x1a, 0x09, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x41, 0x63, 0x6b, 0x12, 0x32, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x13, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x52, 0x50,
	0x43, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x0c, 0x5a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GRPC_proto_proto_rawDescOnce sync.Once
	file_GRPC_proto_proto_rawDescData = file_GRPC_proto_proto_rawDesc
)

func file_GRPC_proto_proto_rawDescGZIP() []byte {
	file_GRPC_proto_proto_rawDescOnce.Do(func() {
		file_GRPC_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_GRPC_proto_proto_rawDescData)
	})
	return file_GRPC_proto_proto_rawDescData
}

var file_GRPC_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GRPC_proto_proto_goTypes = []interface{}{
	(*BidInfo)(nil),       // 0: GRPC.BidInfo
	(*Ack)(nil),           // 1: GRPC.Ack
	(*ResultRequest)(nil), // 2: GRPC.ResultRequest
	(*CurrentResult)(nil), // 3: GRPC.CurrentResult
}
var file_GRPC_proto_proto_depIdxs = []int32{
	0, // 0: GRPC.AuctionService.Bid:input_type -> GRPC.BidInfo
	2, // 1: GRPC.AuctionService.Result:input_type -> GRPC.ResultRequest
	1, // 2: GRPC.AuctionService.Bid:output_type -> GRPC.Ack
	3, // 3: GRPC.AuctionService.Result:output_type -> GRPC.CurrentResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GRPC_proto_proto_init() }
func file_GRPC_proto_proto_init() {
	if File_GRPC_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GRPC_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GRPC_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GRPC_proto_proto_goTypes,
		DependencyIndexes: file_GRPC_proto_proto_depIdxs,
		MessageInfos:      file_GRPC_proto_proto_msgTypes,
	}.Build()
	File_GRPC_proto_proto = out.File
	file_GRPC_proto_proto_rawDesc = nil
	file_GRPC_proto_proto_goTypes = nil
	file_GRPC_proto_proto_depIdxs = nil
}
